version: 2.1

orbs:
  maven: circleci/maven@1.3.0
  codecov: codecov/codecov@3.2.2

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - codecov/upload
      - run:
          name: CheckStyle
          command: mvn checkstyle:checkstyle

workflows:
  sample:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master